### ISSUE TITLE
SkyBison + NERDTree netrw hacking doesn't seem to work

### ISSUE THREAD

**Issue by hoelzro** [paradigm/SkyBison#15]
I often use `:e .` to open a NERDTree browser in the current window.  When doing this from SkyBison, the NERDTree is not displayed (opening another SkyBison prompt and closing it right away will cause it to display, but a CTRL-L does not).

**Comment by paradigm** [comment]
Even without NERDTree, it doesn't seem as though `:e` in SkyBison will open a directory in netrw as it normally does.  I never use either netrw or NERDTree so I never thought to check.  I'll see if I can figure out what causes netrw to activate and fix that, then try NERDTree after that.

**Comment by paradigm** [comment]
It seems netrw is depending on the `:e` command _not_ happening in a `:try/:catch` for whatever it is doing.  I refactored so the cmdline is run outside of the `:try/:catch` I was using to nab `<c-c>`'s (to treat them like `<esc>`) and that seems to have fixed netrw.  My guess is NERDTree is triggered the same way and that this will fix it as well.  Mind checking if NERDTree is also fixed and reporting back?

**Comment by hoelzro** [comment]
Yup, that fixed it!  Thanks for addressing the issue so quickly!
