### ISSUE TITLE
Ignore case

### ISSUE THREAD

**Issue by AeliusSaionji** [paradigm/SkyBison#16]
Can you add the option to ignore case?

Thanks

**Comment by paradigm** [comment]
SkyBison respects the `ignorecase` and `smartcase` settings - see the `:help` for both if you're not familiar with them.  If you don't want them enabled in general, but only for SkyBison, you could wrap your mappings to call SkyBison with commands to set/disable the setting accordingly.

I believe this should suffice and there isn't any need to add code within SkyBison to handle this; however, if you disagree, I'd be happy to discuss further.
