### ISSUE TITLE
Advanced ex commands get mangled

### ISSUE THREAD

**Issue by alpha123** [paradigm/SkyBison#18]
Steps to reproduce:
- Set SkyBison to replace the default ex command line (e.g. with `nnoremap : :<C-u>call SkyBison("")<CR>`).
- Attempted a complicated ex command like :.+3d.

The command appears to get completely and arbitrarily mangled. As soon as I hit the '3' in :.+3d above, my command line turns into : &.

**Comment by jamessan** [comment]
It's not getting mangled.  g:skybison_numberselect is enabled and when you've typed `:.+`, item number 3 is `&`, like below (although 9 will likely vary):

```
1 .+!
2 #
3 &
4 *
5 <
6 =
7 >
8 @
9 AddTabularPattern
-- more --
:.+_
```

When you type 3, the cmdline is replaced with `&` as you requested.

In order to dynamically disable g:skybison_numberselect, press `<C-g>`.  Pressing it again will re-enable number selection.

**Comment by alpha123** [comment]
Oh, you're quite right. That's embarrassing. This can definitely be tagged as invalid.

**Comment by jamessan** [comment]
Don't worry.  I had the same confusion a while back, which is why the toggle key exists now. :)

I do wonder whether it's better to default `g:skybison_numberselect` off since the behavior can be pretty non-obvious if you aren't expecting it, especially in your scenario.

**Comment by paradigm** [comment]
I'm worried that changing the default now will confuse/upset end-users who both want it to act the way it now defaults and who have not configured it to be explicitly set.  I could see some semi-legitimate frustration if someone updated the plugin only to find that a feature they liked appears to be gone.  True, they could look at the change log or documentation to figure out how to re-enable it - but they'd be happier if it just didn't change.

However, this is certainly not the first time someone's run into this kind of issue.  I've been muddling over making a new "2.0" version with a significant number of feature improvements - I'll definitely consider changing the default at that time.

**Comment by alpha123** [comment]
One possibility is to only allow the number select thing for command arguments, as opposed to the command itself.

For example, `:` would display all available commands as it does currently, but numbers wouldn't select one. Next if the user enters `b` so the command line now looks like `:b`, it would have numbers select an argument.

This is a little more complicated than currently, but I think it's very intuitive. It would combine the best of both: commands like `:32` or `:.,.+12d` would work quickly and easily, but you'd still have the convenience of being able to complete ambiguous partially entered buffer names, file names, etc.

**Comment by paradigm** [comment]
Hmm, well, using numbers to select something when the cmdline is empty doesn't make any sense.  There could be value in having it act differently in that situation.  The main downside is that it makes things a bit more complicated/confusing.  I'll think about it.

I've got a semi-major rewrite in mind that might get done in the next few months - that'd be a good time to include changes like this.
