### ISSUE TITLE
Skybison window shows relativenumber

### ISSUE THREAD

**Issue by joakin** [paradigm/SkyBison#7]
Hi there, nice work with skybison!

I have on my config:

```
set relativenumber
```

When I invoke the skybison window, it shows me the relative line numbers, making it really ugly.

![tmp](https://f.cloud.github.com/assets/657839/71460/7ec0ff16-5fe9-11e2-85dc-9d50ccc700f3.png)

To fix it, it's as simple as adding

```
set norelativenumber
```

In here: https://github.com/paradigm/SkyBison/blob/master/plugin/skybison.vim#L64

It would be great if this could be added, If you want me I can fork and make a pull request.

Thanks for this, and also for the great multicursor plugin!

**Comment by paradigm** [comment]
Ooops.  I had a feeling I had forgotten about some settings.  Fixed it in 

https://github.com/paradigm/SkyBison/commit/36f6bb54fb0fe929e8ffd0bd841af2e7ab0a21c9

Thanks for bringing it to my attention!  Glad to hear you're enjoying my plugins :)
